version: '3.8'
services:
  db:
    image: mariadb:10.6
    restart: always
    env_file:
      - .env.development
    volumes:
      - ./initial_data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./initial_data/:/initial_data/
    ports:
      - 3306:3306
